# Generated by Django 3.2.3 on 2021-06-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_user_signin_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('assign_vehicle', models.CharField( max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('contract_number', models.IntegerField()),
                ('license_number', models.IntegerField()),
                ('issue_date', models.DateField(max_length=100)),
                ('expiration_date', models.DateField(max_length=100)),
                ('join_date', models.DateField(max_length=100)),
                ('leave_date', models.DateField(max_length=100)),
                ('password', models.IntegerField()),
                ('radio', models.CharField(max_length=100)),
                ('emergency_contact_details', models.CharField(max_length=100)),
                ('driver_image', models.ImageField(blank=True, null=True, upload_to='driver_image/%Y/%m/%d')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='document_file/%Y/%m/%d')),
                ('upload_license_image', models.ImageField(blank=True, null=True, upload_to='upload_license_image/%Y/%m/%d')),
            ],
        ),
    ]
