# Generated by Django 3.2.3 on 2021-06-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_add_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('is_admin', models.CharField(max_length=100)),
                ('permissiom', models.CharField(max_length=100)),
                ('assign_vehicle1', models.CharField(max_length=100)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='user_image/%Y/%m/%d')),
            ],
        ),
    ]
