# Generated by Django 3.2.3 on 2021-06-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0006_rename_first_name_add_user_first_name1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_user',
            old_name='permissiom',
            new_name='permission',
        ),
    ]
