# Generated by Django 3.2.3 on 2021-06-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0009_add_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_customer',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
