# Generated by Django 3.2.3 on 2021-06-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0010_alter_add_customer_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manage_Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_vehicle', models.CharField(max_length=100)),
                ('income_type', models.CharField(max_length=100)),
                ('milege', models.IntegerField()),
                ('income_date', models.DateField(max_length=100)),
                ('income_amount', models.IntegerField()),
                ('total_tax', models.IntegerField()),
                ('total_tax_charge', models.IntegerField()),
                ('total_amount', models.IntegerField()),
            ],
        ),
    ]
