# Generated by Django 3.2.3 on 2021-06-16 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0012_manage_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manage_expense',
            old_name='date',
            new_name='expense_date',
        ),
    ]
