# Generated by Django 3.2.3 on 2021-06-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0013_rename_date_manage_expense_expense_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_New_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_customer', models.CharField(max_length=100)),
                ('select_vehicle', models.CharField(max_length=100)),
                ('pickup_date_time', models.CharField(max_length=100)),
                ('dropoff_date_time', models.CharField(max_length=100)),
                ('select_driver', models.CharField(max_length=100)),
                ('num_of_travellers', models.CharField(max_length=100)),
                ('pickup_address', models.CharField(max_length=100)),
                ('dropoff_address', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
    ]
