# Generated by Django 3.2.3 on 2021-06-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0014_add_new_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Booking_quotation1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_customer1', models.CharField(max_length=100)),
                ('select_vehicle1', models.CharField(max_length=100)),
                ('pickup_date_time1', models.CharField(max_length=100)),
                ('dropoff_date_time1', models.CharField(max_length=100)),
                ('select_driver1', models.CharField(max_length=100)),
                ('num_of_travellers1', models.CharField(max_length=100)),
                ('type_of_day1', models.CharField(max_length=100)),
                ('trip_milege1', models.CharField(max_length=100)),
                ('waiting_time1', models.CharField(max_length=100)),
                ('amount1', models.IntegerField()),
                ('total_tax1', models.IntegerField()),
                ('total_tax_charge1', models.IntegerField()),
                ('total_amount1', models.IntegerField()),
                ('pickup_address1', models.CharField(max_length=100)),
                ('dropoff_address1', models.CharField(max_length=100)),
                ('notes1', models.CharField(max_length=100)),
            ],
        ),
    ]
