# Generated by Django 3.2.3 on 2021-06-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0015_add_booking_quotation1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_image', models.ImageField(blank=True, null=True, upload_to='vendor_image/%Y/%m/%d')),
                ('vendor_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('type', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
