# Generated by Django 3.2.3 on 2021-06-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0016_add_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_vehicle', models.CharField(max_length=100)),
                ('fuel_tank', models.CharField(max_length=100)),
                ('fuel_tank1', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('qty_gallon', models.CharField(max_length=100)),
                ('start_meter', models.CharField(max_length=100)),
                ('cost_unit', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
            ],
        ),
    ]
