# Generated by Django 3.2.3 on 2021-06-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0017_add_fuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='edit_profile1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_image/%Y/%m/%d')),
                ('languages', models.CharField(max_length=100)),
            ],
        ),
    ]
