# Generated by Django 3.2.3 on 2021-06-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0018_edit_profile1'),
    ]

    operations = [
        migrations.CreateModel(
            name='edit_password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock', models.CharField(max_length=100)),
            ],
        ),
    ]
