# Generated by Django 3.2.3 on 2021-06-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0019_edit_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg_manage_vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_Maker', models.CharField(max_length=100)),
                ('Vehicle_Model', models.CharField(max_length=100)),
                ('Vehicle_Type', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('License_Plate', models.CharField(max_length=100)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='filepath')),
                ('Assigned_Driver', models.CharField(max_length=100)),
                ('Group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='reg_vehicle_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Note', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='reg_vehicle_inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle', models.CharField(max_length=100)),
                ('Registration_Number', models.CharField(max_length=100)),
                ('ReviewBy', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='reg_vehicle_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_Type', models.CharField(max_length=100)),
                ('Display_Name', models.CharField(max_length=100)),
                ('No_of_Seats', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='filepath')),
            ],
        ),
    ]
