# Generated by Django 3.2.3 on 2021-06-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0020_reg_manage_vehicle_reg_vehicle_group_reg_vehicle_inspection_reg_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_driver',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
