# Generated by Django 3.2.3 on 2021-06-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0021_alter_add_driver_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_driver',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='add_driver',
            name='issue_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='add_driver',
            name='join_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='add_driver',
            name='leave_date',
            field=models.DateField(null=True),
        ),
    ]
