# Generated by Django 3.2.3 on 2021-06-22 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0022_auto_20210622_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_driver',
            old_name='radio',
            new_name='female',
        ),
        migrations.AddField(
            model_name='add_driver',
            name='male',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
