# Generated by Django 3.2.3 on 2021-06-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0023_auto_20210622_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_driver',
            old_name='female',
            new_name='radio',
        ),
        migrations.RemoveField(
            model_name='add_driver',
            name='male',
        ),
    ]
