# Generated by Django 3.2.3 on 2021-06-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0027_alter_reg_manage_vehicle_registration_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg_manage_vehicle',
            old_name='Vehicle_Engine_Type',
            new_name='Assigned_Driver',
        ),
        migrations.RemoveField(
            model_name='reg_manage_vehicle',
            name='average_miles',
        ),
        migrations.RemoveField(
            model_name='reg_manage_vehicle',
            name='initial_milege',
        ),
        migrations.RemoveField(
            model_name='reg_manage_vehicle',
            name='license_expiry',
        ),
        migrations.RemoveField(
            model_name='reg_manage_vehicle',
            name='registration_expiry',
        ),
        migrations.RemoveField(
            model_name='reg_manage_vehicle',
            name='vehicle_horse_power',
        ),
        migrations.RemoveField(
            model_name='reg_manage_vehicle',
            name='vehicle_year',
        ),
        migrations.RemoveField(
            model_name='reg_manage_vehicle',
            name='vin',
        ),
    ]
