# Generated by Django 3.2.3 on 2021-06-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0030_auto_20210625_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='Air_conditioner_working_or_not',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='Anyofour_powertools',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='Automaticlocks_alarmworking',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='Car_mats_Car_seat_covers',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='Condition_or_carseats',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='Damagetoexterior_ofcarsdents_scratches_brokenlights_etc',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='DateTime_Incomig',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='DateTime_Outgoing',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='Extension_leads',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='Fuel_level_Incoming',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='Fuel_level_outgoing',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='Interior_Lights',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='Interior_damages',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='Inventor_cigerette',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='Ladders_extension_ladder',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='Light_Indicators',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='Lights_headlights_working',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='Meter_Reading_Incoming',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='Petrol_card',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='Suspension',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='Tool_boxes',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='TyresNew_need_replacing',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='Windows_working_or_not_anydamages_windowtints',
        ),
        migrations.RemoveField(
            model_name='reg_vehicle_inspection',
            name='oil_check',
        ),
    ]
