# Generated by Django 3.2.3 on 2021-07-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0035_auto_20210629_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
            ],
        ),
    ]
