# Generated by Django 3.2.3 on 2021-07-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0036_add_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_fuel',
            name='fuel_image',
            field=models.ImageField(blank=True, null=True, upload_to='fuel_image/%Y/%m/%d'),
        ),
    ]
